name       : openjdk-8
version    : 8.112
release    : 9
source     :
    - https://solus-project.com/sources/jdk8u112.tar.xz : 84750c9c7d3db46e2ea03795b3e41b280b7ef02ff2c4e7e0aed3724e0c29eb70
    - https://solus-project.com/sources/corba-8u112-b16.tar.xz : c91fa9d13b3da5b258a07c98ea010fcf9c86fb20f72b0aadf5b6f1654e48e50d
    - https://solus-project.com/sources/hotspot-8u112-b16.tar.xz : aa10d8b080ccf22d46a4234fb0198be009330ed46cdca1d7030deb7779f49612
    - https://solus-project.com/sources/jaxp-8u112-b16.tar.xz : f353004cf876c7bcd311f5e595a72c006c7b5e9c900a2be70c422adf401e5e36
    - https://solus-project.com/sources/jaxws-8u112-b16.tar.xz : da4d3bbf29607013149c931af2fca7217c3c3fa3b23c01742b9785f7f1166eb8
    - https://solus-project.com/sources/jdk-8u112-b16.tar.xz : 93d2ddfbd1350ba44c404a8a7bcb6927eb0324fc36d11ab4b53cdcf9a2f73d35
    - https://solus-project.com/sources/langtools-8u112-b16.tar.xz : a9293cc42106f1804145e0066983b09e322d1a92613c5a9127f0a891f57f4f2b
    - https://solus-project.com/sources/nashorn-8u112-b16.tar.xz : c003472f4d4e9754880add97f95b6e46802ef2d5d3d99afdb5670a8e2084122b
license    : GPL-2.0-with-classpath-exception
component  : programming.java
summary    : Open implementation of Oracle's Java Development Kit
description: |
    Open implementation of Oracle's Java Development Kit
builddeps  :
    - cups-devel
    - giflib-devel
    - openjdk-8-devel
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - p7zip
setup      : |
    unset LD_AS_NEEDED
    _SOLJVM_VERSION="8u112-b16"
    for subproject in corba hotspot jaxp jaxws langtools jdk nashorn; do
      mkdir -pv ${subproject} &&
      tar -xf $sources/${subproject}-${_SOLJVM_VERSION}.tar.xz --strip-components=1 -C ${subproject}
    done
    unset _SOLJVM_VERSION
    unset JAVA_HOME
    sh ./configure --with-update-version=112 \
        --with-build-number=b16 \
        --with-milestone=fcs \
        --enable-unlimited-crypto \
        --with-zlib=system \
        --with-giflib=system \
        --with-boot-jdk=%libdir%/openjdk-8/ \
        --with-cacerts-file=%libdir%/openjdk-8/jre/lib/security/cacerts \
        --with-extra-cflags="-std=c++98 -Wno-error -fno-delete-null-pointer-checks -fno-lifetime-dse" \
        --with-extra-cxxflags="-std=c++98 -fno-delete-null-pointer-checks -fno-lifetime-dse" \
        --with-extra-ldflags="$LDFLAGS"
build      : |
    unset LD_AS_NEEDED
    CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    make bootcycle-images SCTP_WERROR= DISABLE_HOTSPOT_OS_VERSION_CHECK=ok JOBS=$(echo %JOBS% | sed -e 's/-j//')
install    : |
    # remove redundant *.diz and *.debuginfo files
    find . -iname "*.diz" -exec rm -f {} \;
    find . -iname '*.debuginfo' -exec rm {} \;
    # install jvm
    install -d -D -m 00755 $installdir/%libdir%
    make install INSTALL_PREFIX=$installdir/usr
    rm -rf $installdir/usr/bin/*
    mv $installdir/usr/jvm/openjdk-1.8.0_112 $installdir/%libdir%/openjdk-8
    rmdir $installdir/usr/jvm
    pushd $installdir/usr/bin
    for i in $installdir/%libdir%/openjdk-8/bin/*; do
      ln -sf %libdir%/openjdk-8/bin/`basename $i` .
    done
    popd
    mkdir -p $installdir/usr/share/doc/openjdk-8
    mkdir -p $installdir/usr/include/openjdk-8
    mkdir -p $installdir/usr/share/licenses/openjdk-8
    cp -r ./build/linux-x86_64-normal-server-release/jdk/include/* $installdir/usr/include/openjdk-8/
    # License
    cp LICENSE $installdir/usr/share/licenses/openjdk-8
    # Man pages
    for dir in ./build/linux-x86_64-normal-server-release/images/j2re-image/man/man1/ \
               ./build/linux-x86_64-normal-server-release/images/j2sdk-image/man/man1/
    do
      pushd $dir
      for i in *.1
        do install -D -m 644 $i $installdir/usr/share/man/man1/$i
      done
      popd
    done
    # http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1437
    find $installdir -iname '*.jar' -exec chmod ugo+r {} \;

    install -D -m 00644 $pkgfiles/java-jar.desktop $installdir/usr/share/applications/java-jar.desktop
