name       : openjdk-8
version    : 8.162
release    : 12
source     :
    - https://solus-project.com/sources/java/jdk8u162-b01.tar.bz2 : 0ac924d7b8b6459cac6a94f2bb4cc81b2441828b70179399fe616425f1f81ee4
    - https://solus-project.com/sources/java/corba-u162-b01.tar.bz2 : 661be9bb06a10d02a8f6ef38da13ebd2e481a43f2989bdf3f0267dc29873f1cd
    - https://solus-project.com/sources/java/hotspot-u162-b01.tar.bz2 : d43242a032eba7dc74d73cbe49b06a1d10177d35ea2eb127372aebb16cdce902
    - https://solus-project.com/sources/java/jaxp-u162-b01.tar.bz2 : 555fd4a1245b8ad686738cd4b5e4be772d0fe1aaaeb2b6cf01a27c001f03d34b
    - https://solus-project.com/sources/java/jaxws-u162-b01.tar.bz2 : 545340b42cf5a6da0e518412e05e664ca0e39e30f3b9e1e3f8bf6010be89ceec
    - https://solus-project.com/sources/java/jdk-u162-b01.tar.bz2 : 4655f9f0016f4dd6155d0ccc451cce4fa9709649bac4d85e7180cffeac4cacb7
    - https://solus-project.com/sources/java/langtools-u162-b01.tar.bz2 : 704beb0b8e0f35f0905d8cfda542ebb185a0531b01577108d8efdbc2794f5477
    - https://solus-project.com/sources/java/nashorn-u162-b01.tar.bz2 : 5574450699bcd82c2427bc8bb244cec8bd2581c147886dbc9e2db1d91758caed
license    : GPL-2.0-with-classpath-exception
component  : programming.java
summary    : Open implementation of Oracle's Java Development Kit
description: |
    Open implementation of Oracle's Java Development Kit
builddeps  :
    - cups-devel
    - giflib-devel
    - openjdk-8-devel
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xrender)
    - pkgconfig(xt)
    - pkgconfig(xtst)
    - p7zip
setup      : |
    # Prep input tarballs
    unset LD_AS_NEEDED
    _SOLJVM_VERSION="u162-b01"
    for tarball in corba hotspot jaxp jaxws langtools jdk nashorn; do
        mkdir -pv ${tarball} &&
        tar -xf $sources/${tarball}-${_SOLJVM_VERSION}.tar.bz2 --strip-components=1 -C ${tarball}
    done
    unset _SOLJVM_VERSION
    unset JAVA_HOME
    
    # Now configure
    export SANEFLAGS="-std=c++98 -Wno-error -fno-delete-null-pointer-checks -fno-lifetime-dse"
    bash ./configure --prefix="$installdir/usr" \
        --with-update-version=162 \
        --with-build-number=b01 \
        --with-milestone=solus \
        --with-zlib=system \
        --with-giflib=system \
        --enable-unlimited-crypto \
        --with-cacerts-file=%libdir%/openjdk-8/jre/lib/security/cacerts \
        --with-jobs=%YJOBS% \
        --with-extra-cflags="$CFLAGS $SANEFLAGS" \
        --with-extra-cxxflags="$CXXFLAGS $SANEFLAGS" \
        --with-extra-ldflags="$LDFLAGS"
build      : |
    unset LD_AS_NEEDED
    make SCTP_WERROR= DISABLE_HOTSPOT_OS_VERSION_CHECK=ok all WARNINGS_ARE_ERRORS=
install    : |
    install -d -D -m 00755 $installdir/%libdir%
    make install
    
    # Binaries
    rm -rf $installdir/usr/bin/*
    mv $installdir/usr/jvm/openjdk-1.8.0_162-solus $installdir/%libdir%/openjdk-8
    rmdir $installdir/usr/jvm
    pushd $installdir/usr/bin
    for i in $installdir/%libdir%/openjdk-8/bin/*; do
      ln -sf %libdir%/openjdk-8/bin/`basename $i` .
    done
    popd
    
    # Docs
    install -m 00644 -D LICENSE $installdir/usr/share/doc/openjdk-8/LICENSE

    # Move into build dir
    pushd build/linux-x86_64-normal-server-release

    # Chuck the headers in
    install -D -d -m 00755 $installdir/usr/include/openjdk-8
    cp -ra jdk/include/* $installdir/usr/include/openjdk-8/.

    # Sort out the manpages
    install -D -d -m 00755 $installdir/usr/share/man/man1
    install -m 00644 images/j2re-image/man/man1/*.1 $installdir/usr/share/man/man1/.
    install -m 00644 images/j2sdk-image/man/man1/*.1 $installdir/usr/share/man/man1/.
    
    # Add java-jar.desktop into usable apps
    install -D -m 00644 $pkgfiles/java-jar.desktop $installdir/usr/share/applications/java-jar.desktop
